import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NandBox",
  description: "Generated by create next app",
  icons: "/nandbox_icon.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="scroll-smooth">
      <body
        className={inter.variable}
        style={{
          margin: 0,
          padding: 0,
          height: "100vh",
          width: "100%"
        }}
      >
        {children}
      </body>
    </html>
  );
}
